import tkinter as tk
from tkinter import mainloop as show
from tkinter import *

window = tk.Tk()
window.title("")
window.geometry("1920x1080")

"""
frame_topo = tk.Frame(window, bg="lightgrey")
frame_topo.pack(fill="x")

frame_corpo = tk.Frame(window, bg="lightblue")
frame_corpo.pack(fill="x")

tk.Label(frame_topo, text="Topo", font=("Comic Sans", 24), bg="lightgrey").pack()
tk.Label(frame_corpo, text="Corpo", font=("Comic Sans", 24), bg="lightblue").pack()
show()
"""

menu = tk.Menu(window)

menu_arquivo = tk.Menu(menu, tearoff=0)
menu_arquivo.add_command(label="Novo")
menu_arquivo.add_command(label="Nova Janela")
menu_arquivo.add_command(label="Abrir...")
menu_arquivo.add_command(label="Guardar")
menu_arquivo.add_command(label="Guardar Como...")
menu_arquivo.add_separator()
menu_arquivo.add_command(label="Configuração de Página...")
menu_arquivo.add_command(label="Imprimir...")
menu_arquivo.add_separator()
menu_arquivo.add_command(label="Sair", command=window.quit)
menu.add_cascade(label="Arquivo", menu=menu_arquivo)
menu_editar = tk.Menu(menu, tearoff=0)
menu_editar.add_command(label="Anular")
menu_editar.add_command(label="Cortar")
menu_editar.add_command(label="Copiar")
menu_editar.add_command(label="Colar")
menu_editar.add_command(label="Eliminar")
menu_editar.add_separator()
menu_editar.add_command(label="Procurar com Bing...")
menu_editar.add_command(label="Localizar...")
menu_editar.add_command(label="Localizar Seguinte")
menu_editar.add_command(label="Localizar Anterior")
menu_editar.add_command(label="Substituir...")
menu_editar.add_command(label="Ir para...")
menu_editar.add_separator()
menu_editar.add_command(label="Selecionar Tudo")
menu_editar.add_command(label="Hora/Data")
menu.add_cascade(label="Editar", menu=menu_editar)
menu_formatar = tk.Menu(menu, tearoff=0)
menu_formatar.add_command(label="Moldar Texto")
menu_formatar.add_command(label="Tipo de letra...")
menu.add_cascade(label="Formatar", menu=menu_formatar)
menu_ver = tk.Menu(menu, tearoff=0)
menu_zoom = tk.Menu(menu_ver, tearoff=0)
menu_ver.add_cascade(label="Zoom", menu=menu_zoom)
menu_zoom.add_command(label="Ampliar")
menu_zoom.add_command(label="Reduzir")
menu_zoom.add_command(label="Restaurar Zoom Predefinido")
menu_ver.add_command(label="Barra de Estado")
menu.add_cascade(label="Ver", menu=menu_ver)
menu_ajuda = tk.Menu(menu, tearoff=0)
menu_ajuda.add_command(label="Ver Ajuda")
menu_ajuda.add_command(label="Enviar Comentários")
menu_ajuda.add_separator()
menu_ajuda.add_command(label="Acerca do Bloco de Notas")
menu.add_cascade(label="Ajuda", menu=menu_ajuda)
window.config(menu=menu)
show()
